name: Test Install publish-release

on:
    workflow_dispatch:

jobs:
    setup:
        runs-on: ubuntu-latest
    
        permissions:
            contents: write # needed to write releases
            id-token: write # needed for keyless signing
            packages: write # needed for pushing the images to ghcr.io
    
        env:
            COSIGN_YES: "true"
    
        steps:
            - name: Install release notes
              uses: puerco/release-actions/setup-release-notes@HEAD
